import { Boundary } from '#/ui/boundary';

const TITLES = ['Next.js Playground', 'Generated with ImageResponse', 'OG ❤ JSX'];

export default function Page() {
  return (
    <Boundary label="og/page.tsx (Server Environment)">
      <div className="flex flex-col gap-6">
        <p className="text-sm leading-7 text-gray-300">
          Open Graph images are what shows up when your link is shared on social
          media. Next.js can generate them <strong className="text-gray-100">dynamically</strong>{' '}
          from JSX + CSS using the{' '}
          <code className="rounded bg-gray-800 px-1 py-0.5 font-mono text-xs text-gray-200">
            ImageResponse
          </code>{' '}
          constructor from{' '}
          <code className="rounded bg-gray-800 px-1 py-0.5 font-mono text-xs text-gray-200">
            next/og
          </code>
          .
        </p>

        <div className="flex flex-col gap-3">
          <span className="text-xs font-semibold uppercase tracking-wider text-gray-500">
            Live — generated by this repo&apos;s /api/og route
          </span>
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
            {TITLES.map((t) => (
              <div key={t} className="flex flex-col gap-1">
                {/* Each src hits an ImageResponse route that renders a PNG. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`/api/og?title=${encodeURIComponent(t)}`}
                  alt={`OG image: ${t}`}
                  width={1200}
                  height={630}
                  className="w-full rounded-lg border border-gray-800"
                />
                <span className="font-mono text-[11px] text-gray-500 break-all">
                  /api/og?title={encodeURIComponent(t)}
                </span>
              </div>
            ))}
          </div>
        </div>

        <div className="flex flex-col gap-2">
          <span className="text-xs font-semibold uppercase tracking-wider text-gray-500">
            File convention: opengraph-image.tsx
          </span>
          <p className="text-xs leading-6 text-gray-500">
            Drop an{' '}
            <code className="font-mono text-gray-400">opengraph-image.tsx</code>{' '}
            in any route folder; its default export returns an{' '}
            <code className="font-mono text-gray-400">ImageResponse</code>. The
            more specific file wins over ones higher in the tree.
          </p>
          <pre className="overflow-x-auto rounded-lg border border-gray-800 bg-gray-950/60 p-4 font-mono text-xs leading-6 text-gray-400">
{`// app/blog/[slug]/opengraph-image.tsx
import { ImageResponse } from 'next/og'

export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'

export default async function Image({ params }) {
  const { slug } = await params
  return new ImageResponse(
    (
      <div style={{ fontSize: 128, background: 'white', width: '100%',
                    height: '100%', display: 'flex',
                    alignItems: 'center', justifyContent: 'center' }}>
        {slug}
      </div>
    )
  )
}`}
          </pre>
        </div>

        <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-4">
          <p className="text-xs leading-6 text-gray-500">
            <span className="font-semibold text-gray-400">How it works:</span>{' '}
            <code className="font-mono text-gray-400">ImageResponse</code> uses
            Satori to turn HTML/CSS into a PNG. Only{' '}
            <strong className="text-gray-300">flexbox</strong> and a subset of
            CSS are supported — no{' '}
            <code className="font-mono text-gray-400">display: grid</code>. Also
            available for static OG images: just drop an{' '}
            <code className="font-mono text-gray-400">opengraph-image.jpg</code>{' '}
            file in a route folder.
          </p>
        </div>
      </div>
    </Boundary>
  );
}
